name: Build Android APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Criar Projeto do Zero
        run: |
          # O segredo está no --project-name sound_bit para evitar o erro do print
          flutter create --platforms android --org com.soundbit --project-name sound_bit .
          
      - name: Injetar Código
        run: |
          mkdir -p lib
          echo 'import "package:flutter/material.dart"; void main() => runApp(MaterialApp(home: Scaffold(backgroundColor: Color(0xFFF5F5DC), body: Center(child: Text("SOUND BIT ONLINE", style: TextStyle(color: Colors.grey, fontSize: 20))))));' > lib/main.dart

      - name: Gerar APK
        run: flutter build apk --debug

      - name: Enviar Ficheiro
        uses: actions/upload-artifact@v4
        with:
          name: sound-bit-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          
